### ISSUE TITLE
Reference manual font is not readable with light theme and light background

### ISSUE THREAD

**Issue by paustint** [lukakerr/regxr#11]
The background is semi-transparent with the light theme and if the window is over some other window that is white, the text is not visible enough.

![image](https://user-images.githubusercontent.com/5461649/38848693-9aea51b0-41c5-11e8-9bbb-45f3ae80e805.png)

**Comment by lukakerr** [comment]
Good spot, will fix this up. I noticed you also have the black bars in the window as in #6, what macOS version are running?

**Comment by lukakerr** [comment]
I can't reproduce this, this is what is looks like for me over a pure white background:

<img width="773" alt="screen shot 2018-04-18 at 10 51 33 am" src="https://user-images.githubusercontent.com/20056300/38905855-834db466-42f6-11e8-9a34-6e15462e286f.png">

If you try the [latest release](https://github.com/lukakerr/regxr/releases/tag/v0.0.3) and it still occurs, leave a comment
