### ISSUE TITLE
Test text losing style

### ISSUE THREAD

**Issue by citosid** [lukakerr/regxr#12]
When using the latest version, after the regular expression is updated, the test text loses style:

![regxr](https://user-images.githubusercontent.com/201430/38896546-fedd2e9a-4260-11e8-8c94-0d278c2a7e6a.gif)

I can't add new lines either in the test text.

**Comment by lukakerr** [comment]
This should be fixed in [the latest release](https://github.com/lukakerr/regxr/releases/tag/v0.0.3)
