### ISSUE TITLE
Black bars in input fields

### ISSUE THREAD

**Issue by nvanmeurs** [lukakerr/regxr#6]
![Black bars in input fields](https://i.imgur.com/vtXnMpv.png)

**Comment by lukakerr** [comment]
Hmm I can't reproduce this with the same exact text. Do you have an example of steps you took when the bars appeared or how to reproduce it?

**Comment by nvanmeurs** [comment]
Sorry I failed to mention it has nothing to do with the text, it happens as soon as I start the application
<img width="598" alt="regxr2" src="https://user-images.githubusercontent.com/1681034/38801939-723f20b0-416b-11e8-9b72-178e796761d7.png">

**Comment by lukakerr** [comment]
I'm running the same macOS version as well.. strange. I'll have to look into this further. It looks like it may have to do with the scrollbar of both inputs

**Comment by R3l4x3** [comment]
Same here  

<img width="334" alt="bildschirmfoto 2018-04-17 um 11 40 30" src="https://user-images.githubusercontent.com/5042379/38862038-367da870-4234-11e8-99b7-bb20621f8d74.png">

**Comment by lukakerr** [comment]
@nvanmeurs @R3l4x3 could you guys please try this build and let me know if its any better? https://drive.google.com/file/d/13gdX7D7obkIEY3pZ9Sq4Iz5uRSPlH2qo/view?usp=sharing

I can't reproduce it at all on 10.13.4, but people are experiencing it

**Comment by nvanmeurs** [comment]
@lukakerr The issue is resolved for me now, thanks!

**Comment by lukakerr** [comment]
Cool, thanks for that! I'll commit the changes and create a new release
