### ISSUE TITLE
Expression validation sometimes invalid

### ISSUE THREAD

**Issue by cheeaun** [lukakerr/regxr#8]
I'm not sure what's the exact issue but sometimes it says invalid expression, but becomes valid after that.

Using `v0.0.1`:

![apr-16-2018 18-19-01](https://user-images.githubusercontent.com/2296/38803849-0455e902-41a3-11e8-902b-1d9aa8fd9eae.gif)

**Comment by lukakerr** [comment]
Looks like a small bug, should be easy enough to fix

**Comment by lukakerr** [comment]
I believe this has been fixed in [the latest release](https://github.com/lukakerr/regxr/releases/tag/v0.0.3). `a[]` is an invalid expression, which triggers the error message, but `a[^\s]*` etc isn't, and in this release this is correctly expressed
